# Workflow for Terraform process for infrastrcture management

name: Terraform Workflow #name of the workflow

on: #PR event triggers Terraform process
    pull_request:
        branches:
            - main
        paths:
            - 'terraform-nextjs/**'
        types: [opened, synchronize, reopened, closed]

jobs:
    terraform_init-to-terraform_plan:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./terraform-nextjs
        permissions:
            pull-requests: write

        steps:
            - uses: actions/checkout@v7

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v6.2.3
              with:
                aws-region: ca-central-1
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v4
            
            - name: Initialize Terraform
              run: terraform init

            - name: Format Terraform code
              run: terraform fmt -check

            - name: Validate Terraform code
              run: terraform validate

            - name: Terraform Plan
              id: terraform_plan
              run: terraform plan -no-color

            - name: Display Terraform Plan
              uses: actions/github-script@v9
              with:
                github-token: ${{secrets.GITHUB_TOKEN}}
                script: |
                    github.rest.issues.createComment({
                        issue_number: context.issue.number,
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        body: `## Terraform Plan Result\n\`\`\`\n${{ steps.terraform_plan.outputs.stdout }}\n\`\`\``
                    })


    terraform_apply:
        runs-on: ubuntu-latest
        if: github.event.pull_request.merged == true
        needs: terraform_init-to-terraform_plan
        defaults:
            run:
                working-directory: ./terraform-nextjs

        steps:
            - uses: actions/checkout@v7

            - name: Set up Terraform
              uses: hashicorp/setup-terraform@v4

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v6.2.3
              with:
                aws-region: ca-central-1
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

            - name: Initialize Terraform
              run: terraform init

            - name: apply Terraform
              run: terraform apply -auto-approve

            - name: Build Next.js static files
              run: |
                npm install
                npm run build
              working-directory: ./nextjs-blog

            - name: Sync static files to S3 bucket
              run: aws s3 sync out/ s3://static-website-portfolio-client
              working-directory: ./nextjs-blog
              
            - name: Invalidate CloudFront cache
              run: aws cloudfront create-invalidation --distribution-id E1W8882LFQYXB5 --paths "/*"